image: Visual Studio 2019

skip_branch_with_pr: true
skip_tags: true
skip_commits:
  files:
    - '**/*.md'
    - docs/*

install:	
  - choco install dotnet-sdk --version 5.0.100

environment:
  Appveyor: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

nuget:
  disable_publish_on_pr: true

build_script:
  - cmd: dotnet build Build.csproj -c Release /p:CI=true /p:GeneratePackageOnBuild=false
  - cmd: dotnet test Build.csproj -c Release /p:CI=true

test: off
artifacts:
- path: .\.nupkgs\*.nupkg
